### ISSUE TITLE
Fails with Cucumber 6.x

### ISSUE THREAD

**Issue by ThreeAxis** [mechero/spring-boot-cucumber#3]
Hi,

Great project and very well written documentation on https://thepracticaldeveloper.com/cucumber-tests-spring-boot-dependency-injection/

I was able to use your guide to fix a tricky problem in my own code.

Just wanted to let you know that your code doesn't run with the current (6.x) version of Cucumber. You may want to look into this, to keep your work current.

Three Axis

**Comment by mechero** [comment]
Thanks! I'll definitely have a look at this soon to fix it.
